apiVersion: v1
kind: Service
metadata:
 name: mongodb
 namespace: roboshop
spec:
  selector:
    project: roboshop
    env: dev
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017