apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
  # property-like keys; each key maps to a simple value
    project: roboshop
    env: dev
    component: catalogue
data: 
  MONGO: "true"
  MONGO_URL: {{ .Values.configMap.MONGO_URL }}
