apiVersion: v1
kind: Service
metadata:
 name: catalogue
 namespace: roboshop
 labels:
   project: roboshop
   env: dev
   component: catalogue
spec:
  selector:
    project: roboshop
    env: dev
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080